"use client";

import { useEffect, useState } from "react";

type Waiter = { id: string; name: string; username: string; area: "salao" | "copa"; tablesCount: number };
type Form = { id?: string; name: string; username: string; area: "salao" | "copa"; password: string };
const empty: Form = { name: "", username: "", area: "salao", password: "" };

export default function AdminForm() {
  const [waiters, setWaiters] = useState<Waiter[]>([]);
  const [editing, setEditing] = useState<Form | null>(null);
  const [tableOpen, setTableOpen] = useState(false);
  const [table, setTable] = useState({ number: "", name: "", area: "salao" });
  async function refresh() { const response = await fetch("/api/users"); if (response.ok) { const data = await response.json(); setWaiters(data.filter((item: Waiter) => item.area)); } }
  useEffect(() => { void refresh(); }, []);
  async function saveWaiter(event: React.FormEvent) { event.preventDefault(); if (!editing) return; const response = await fetch("/api/users", { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing.id ? editing : { ...editing, role: "garcom" }) }); const result = await response.json(); if (!response.ok) return alert(result.error); setEditing(null); void refresh(); }
  async function saveTable(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/tables", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...table, number: Number(table.number) }) }); const result = await response.json(); if (!response.ok) return alert(result.error); alert("Mesa cadastrada. Recarregue a pagina para atualizar o mapa."); setTable({ number: "", name: "", area: "salao" }); setTableOpen(false); }
  return <>
    <button className="mt-2 w-full rounded-xl border border-orange-400/40 bg-orange-500/10 px-3 py-2.5 text-sm font-black text-orange-300 hover:bg-orange-500 hover:text-white" onClick={() => setEditing(empty)}>+ Novo garcom</button>
    <button className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-black text-white hover:bg-white/15" onClick={() => setTableOpen(true)}>+ Nova mesa</button>
    <div className="mt-5 border-t border-white/10 pt-4"><p className="mb-2 text-xs font-black uppercase tracking-widest text-slate-400">Garcons</p>{waiters.map((waiter) => <button key={waiter.id} className="mb-1 flex w-full items-center justify-between rounded-lg bg-white/5 px-2 py-2 text-left hover:bg-white/10" onClick={() => setEditing({ id: waiter.id, name: waiter.name, username: waiter.username, area: waiter.area, password: "" })}><span><strong className="block truncate text-xs">{waiter.name}</strong><small className="text-[11px] text-slate-400">{waiter.area === "copa" ? "Copa" : "Salao"}</small></span><b className="rounded bg-orange-500/20 px-1.5 py-1 text-xs text-orange-300">{waiter.tablesCount}</b></button>)}</div>
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><form className="w-full max-w-md rounded-2xl bg-white p-5 text-slate-900" onSubmit={saveWaiter}><h2 className="mb-4 text-2xl font-black">{editing.id ? "Editar garcom" : "Novo garcom"}</h2><input className="mb-2 w-full rounded-xl border p-2.5" placeholder="Nome" value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} required /><input className="mb-2 w-full rounded-xl border p-2.5" placeholder="Usuario" value={editing.username} onChange={(event) => setEditing({ ...editing, username: event.target.value })} required /><select className="mb-2 w-full rounded-xl border p-2.5" value={editing.area} onChange={(event) => setEditing({ ...editing, area: event.target.value as Form["area"] })}><option value="salao">Salao</option><option value="copa">Copa</option></select><input className="mb-5 w-full rounded-xl border p-2.5" type="password" placeholder={editing.id ? "Nova senha (opcional)" : "Senha"} value={editing.password} onChange={(event) => setEditing({ ...editing, password: event.target.value })} required={!editing.id} /><div className="flex justify-end gap-2"><button type="button" className="rounded-xl px-4 py-2 text-slate-500" onClick={() => setEditing(null)}>Cancelar</button><button className="rounded-xl bg-orange-500 px-5 py-2 font-black text-white">Salvar</button></div></form></div>}
    {tableOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4" onMouseDown={(event) => event.target === event.currentTarget && setTableOpen(false)}><form className="w-full max-w-md rounded-2xl bg-white p-5 text-slate-900" onSubmit={saveTable}><h2 className="mb-4 text-2xl font-black">Nova mesa</h2><input className="mb-2 w-full rounded-xl border p-2.5" type="number" min="1" placeholder="Numero da mesa" value={table.number} onChange={(event) => setTable({ ...table, number: event.target.value })} required /><input className="mb-2 w-full rounded-xl border p-2.5" placeholder="Nome da mesa (opcional)" value={table.name} onChange={(event) => setTable({ ...table, name: event.target.value })} /><select className="mb-5 w-full rounded-xl border p-2.5" value={table.area} onChange={(event) => setTable({ ...table, area: event.target.value })}><option value="salao">Salao</option><option value="copa">Copa</option></select><div className="flex justify-end gap-2"><button type="button" className="rounded-xl px-4 py-2 text-slate-500" onClick={() => setTableOpen(false)}>Cancelar</button><button className="rounded-xl bg-orange-500 px-5 py-2 font-black text-white">Cadastrar</button></div></form></div>}
  </>;
}
