"use client";

import { useEffect, useState } from "react";
import Sidebar, { type SidebarUser } from "../sidebar";

type Stats = { totalTables: number; openTables: number; closedTables: number; totalDishes: number; averageMinutes: number; byWaiter: { name: string; area: string; tables: number; dishes: number; averageMinutes: number }[] };
const today = new Date().toISOString().slice(0, 10);

export default function Dashboard() {
  const [user, setUser] = useState<SidebarUser | null>(null);
  const [date, setDate] = useState(today);
  const [stats, setStats] = useState<Stats | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/auth/me").then(async (response) => { const data = await response.json(); if (!response.ok || data.user?.role !== "admin") throw new Error("Acesso negado"); setUser(data.user); }).catch((cause) => setError(cause.message)); }, []);
  useEffect(() => { if (!user) return; setStats(null); fetch(`/api/dashboard?date=${date}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setStats(data); }).catch((cause) => setError(cause.message)); }, [date, user]);
  if (error) return <main className="grid min-h-screen place-items-center bg-slate-100 p-5"><div className="rounded-2xl bg-white p-8 text-center shadow"><h1 className="text-xl font-black">Acesso restrito</h1><p className="mt-2 text-slate-500">{error}</p><a className="mt-5 inline-block cursor-pointer rounded-xl bg-orange-500 px-4 py-2 font-bold text-white" href="/">Voltar</a></div></main>;
  if (!user || !stats) return <main className="grid min-h-screen place-items-center bg-slate-100 text-slate-500">Carregando dashboard...</main>;
  return <main className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[250px_minmax(0,1fr)]"><Sidebar user={user} /><section className="min-w-0 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-orange-500">Gestao</p><h1 className="text-3xl font-black sm:text-4xl">Dashboard</h1><p className="text-slate-500">Resumo dos atendimentos registrados.</p></div><label className="text-xs font-black uppercase tracking-wider text-slate-500">Data<input className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></header><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Mesas atendidas" value={stats.totalTables} /><Card label="Em atendimento" value={stats.openTables} accent /><Card label="Pratos servidos" value={stats.totalDishes} /><Card label="Tempo medio" value={`${stats.averageMinutes} min`} /></div><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black">Atendimento por garcom</h2>{stats.byWaiter.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Usuario</th><th className="pb-3">Area</th><th className="pb-3">Mesas</th><th className="pb-3">Pratos</th><th className="pb-3">Tempo medio</th></tr></thead><tbody className="divide-y divide-slate-100">{stats.byWaiter.map((waiter) => <tr key={waiter.name}><td className="py-3 font-bold">{waiter.name}</td><td className="py-3">{waiter.area === "copa" ? "Copa" : "Salao"}</td><td className="py-3 font-black text-slate-700">{waiter.tables}</td><td className="py-3 font-black text-orange-600">{waiter.dishes}</td><td className="py-3">{waiter.averageMinutes} min</td></tr>)}</tbody></table></div> : <p className="py-8 text-center text-slate-400">Nao ha atendimentos registrados nesta data.</p>}</section></div></section></main>;
}
function Card({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className={`rounded-2xl border p-5 shadow-sm ${accent ? "border-orange-200 bg-orange-50" : "border-slate-200 bg-white"}`}><p className="text-sm font-bold text-slate-500">{label}</p><strong className="mt-2 block text-3xl font-black">{value}</strong></div>; }
